### ISSUE TITLE
No type control at Input

### ISSUE THREAD

**Issue by us** [almerion/easy-comment#3]

**Comment by hemreari** [comment]
I would like to see more information. Can you provided that?

**Comment by hemreari** [comment]
I think, this should solve the problem: https://github.com/hemreari/easy-comment/commit/92dac66541019f1a5d2015259c9e735fac1d8278

**Comment by us** [comment]
this is what i mentioned
```
Welcome to Easy Comment
Avaible programming languages:

C [1], Python [2], Java [3]

Your choice: a
Enter a file name: a
Enter author: a
Enter creation date: a
Enter a description for your source file: a
You have to choose [1], [2] or [3]

Everything is done, Your file is created.
```

and last update not working!
file creating what is it I think file already creating?
maybe you should say comment or whatever name is it created. It's more meaningful.
